# Generated by Django 5.0.2 on 2024-03-11 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_user_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('event_date', models.CharField(max_length=100)),
                ('event_venue', models.CharField(max_length=100)),
                ('event_time', models.CharField(max_length=100)),
                ('event_price', models.PositiveIntegerField()),
                ('event_desc', models.TextField()),
                ('event_image', models.ImageField(upload_to='event_images/')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
